### ISSUE TITLE
Change Colours?

### ISSUE THREAD

**Issue by wyv3rnnn** [Hexagon/cryptalk#14]
Hello!
I'm wondering if it's possible to change like the colours for the time stamps and messages and help banner. Like which file would it be and how would I go about doing that?

Thanks,
WYV3RN

**Comment by Hexagon** [comment]
Hi!

Colors of "console" messages are all controlled by public/css/default.css. In this File you'll find a couple of default message classes (good, bad, info). 

https://github.com/Hexagon/cryptalk/blob/975dc183771f240b9445c6d082cfb38492605db9/public/css/default.css#L29

Not sure if changing those would be granular enough for your needs, but worth a shot.

If you'd like to elaborate further, the messages are rendered by public/js/console.js (i think, on phone right now so i cant check while writing)
