### ISSUE TITLE
Network breaking

### ISSUE THREAD

**Issue by KonarKorona** [Hexagon/cryptalk#5]
Me and a friend of mine both tried to run this in our own servers. And both times it broke our internet. And it broke so bad on my friend's side that he had to do a factory reset on his router to get anything to work.

Something is causing things to break.

**Comment by Hexagon** [comment]
![Broken internet](http://i.imgur.com/YKlb0nx.png)

@unkelpehr

**Comment by KonarKorona** [comment]
I'm sorry, but I don't speak in picture. Would you mind saying that in a language we are more likely to understand, please?
