### ISSUE TITLE
Error in the container created by docker command

### ISSUE THREAD

**Issue by lapwat** [Hexagon/cryptalk#8]
Good morning,

When I type `docker run -d --restart=always -p 6666:8080 hexagon/cryptalk`, the container crashes.

I get the following logs in the container:

```
cp: can't create directory '/usr/src/app/external-public/css': No such file or directory
cp: can't create directory '/usr/src/app/external-public/gfx': No such file or directory
cp: can't create '/usr/src/app/external-public/index.html': No such file or directory
cp: can't create directory '/usr/src/app/external-public/js': No such file or directory
```

Cheers,
lapwat

**Comment by lapwat** [comment]
You may need to update the Docker Hub image. The latest Docker Hub image was uploaded February the 22nd, whereas the last commit was on December the 4th.

**Comment by Hexagon** [comment]
Fixed
